version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: family-postgres
    volumes:
      - "./postgres:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    restart: always
