version: '3.3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: family-postgres
    volumes:
      - "./postgres:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8.7
    container_name: family-pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_USER: family
      PGADMIN_DEFAULT_EMAIL: application@familyhospital.vn
      PGADMIN_DEFAULT_PASSWORD: family
    restart: always
    tty: true
    depends_on:
      - family-postgres
